# Generated by Django 4.2.14 on 2024-08-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="client_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Email", models.CharField(max_length=30)),
                ("Mobile", models.CharField(max_length=30)),
                ("Username", models.CharField(max_length=30)),
                ("Login_Status", models.BooleanField(default=False)),
            ],
        ),
    ]
