# Generated by Django 4.0.7 on 2024-08-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register',
            name='Password',
            field=models.CharField(default='default_password', max_length=20),
            preserve_default=False,
        ),
    ]
