# Generated by Django 4.0.7 on 2024-08-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0002_client_register_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_register',
            name='Login_Status',
        ),
    ]
