# Generated by Django 4.0.7 on 2024-08-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0003_remove_client_register_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register',
            name='Login_Status',
            field=models.BooleanField(default=False),
        ),
    ]
