# Generated by Django 4.0.7 on 2024-08-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0004_client_register_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Mobile', models.CharField(max_length=10)),
                ('Project_Type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Residential Building', 'Residential Building'), ('Industrial Building', 'Industrial Building'), ('Office', 'Office')], max_length=50)),
                ('Land_Area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Land_Type', models.CharField(choices=[('Agricultural Land', 'Agricultural Land'), ('Brownfield Land', 'Brownfield Land'), ('Contaminated land', 'Contaminated land'), ('Green Belt Land', 'Green Belt Land'), ('Greenfield Land', 'Greenfield Land'), ('Strategic Land', 'Strategic Land')], max_length=50)),
                ('Floors', models.IntegerField()),
            ],
        ),
    ]
