# Generated by Django 4.0.7 on 2024-08-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0005_project_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_register',
            old_name='Land_Area',
            new_name='Land_Area_Sqft',
        ),
    ]
