# Generated by Django 4.0.7 on 2024-08-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0006_rename_land_area_project_register_land_area_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_register',
            name='Project_Approved',
            field=models.CharField(default='No', max_length=4),
        ),
    ]
