# Generated by Django 4.0.7 on 2024-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0007_project_register_project_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Company', models.CharField(max_length=40)),
                ('Mobile', models.CharField(max_length=10)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=8)),
                ('Login_Status', models.BooleanField(default=False)),
            ],
        ),
    ]
