# Generated by Django 4.0.7 on 2024-08-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0008_vendor_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_register',
            old_name='Project_Approved',
            new_name='Manager_Approval',
        ),
    ]
