# Generated by Django 4.0.7 on 2024-08-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0009_rename_project_approved_project_register_manager_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_register',
            name='Design_layout',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='project_register',
            name='Location_Tested',
            field=models.CharField(default='No', max_length=4),
        ),
    ]
