# Generated by Django 4.0.7 on 2024-08-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0010_project_register_design_layout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_register',
            name='Design_layout',
        ),
    ]
