# Generated by Django 4.0.7 on 2024-08-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0011_remove_project_register_design_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_register',
            name='Design_layout',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
