# Generated by Django 4.0.7 on 2024-08-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0012_project_register_design_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Company', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=30)),
                ('Land_Area_Sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Floors', models.IntegerField()),
                ('Cement_Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Sand_Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Stone_Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Brick_Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Paint_Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Total_Estimation', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
