# Generated by Django 4.0.7 on 2024-08-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0013_vendor_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_quotation',
            name='Paint_Price',
        ),
        migrations.RemoveField(
            model_name='vendor_quotation',
            name='Total_Estimation',
        ),
    ]
