# Generated by Django 4.0.7 on 2024-08-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0015_vendor_quotation_paint_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_quotation',
            name='Vendor_Selection',
            field=models.CharField(default='Unselected', max_length=20),
        ),
    ]
