# Generated by Django 4.0.7 on 2024-08-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0016_vendor_quotation_vendor_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_quotation',
            name='Project_Type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
