# Generated by Django 4.0.7 on 2024-08-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0017_vendor_quotation_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_register',
            name='Vendor_Quotation',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
    ]
