# Generated by Django 4.0.7 on 2024-08-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0019_project_register_manager_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_register',
            name='Other_costs',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
    ]
