# Generated by Django 4.0.7 on 2024-08-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0020_project_register_other_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_register',
            name='Client_approved',
            field=models.CharField(default='No', max_length=4),
        ),
        migrations.AddField(
            model_name='project_register',
            name='Manager_Approved',
            field=models.CharField(default='No', max_length=4),
        ),
    ]
