# Generated by Django 4.0.7 on 2024-08-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0021_project_register_client_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_register',
            name='Actual_Quotation',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
    ]
