# Generated by Django 4.0.7 on 2024-08-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KsBuilder', '0022_project_register_actual_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_register',
            name='Profit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
    ]
